name: packer
version: "0.11.0"
summary: tool for creating machine images for multiple platforms
description: Packer is a CLI tool for the automatic creation of identical machine images (single deployable units that contain a pre-configured OS and installed software) for multiple platforms (public cloud providers, private cloud and desktop virtualization solutions) from a single JSON template resp. configuration file.
confinement: strict
grade: devel

apps:
        packer:
                command: packer
                plugs:
                        - home
                        - network

parts:
        packer:
                plugin: go
                source: git://github.com/mitchellh/packer
                source-tag: v0.11.0
                go-importpath: github.com/mitchellh/packer
