name: packer
version: "master"
summary: tool for creating machine images for multiple platforms
description: Packer is a CLI tool for the automatic creation of identical machine images (single deployable units that contain a pre-configured OS and installed software) for multiple platforms (public cloud providers, private cloud and desktop virtualization solutions) from a single JSON template resp. configuration file.
confinement: strict
grade: stable

apps:
  packer:
    command: packer
    plugs:
      - home
      - network

parts:
  packer:
    plugin: go
    source: https://github.com/mitchellh/packer
    source-type: git
    go-importpath: github.com/mitchellh/packer
    go-packages: [github.com/mitchellh/packer]
    go-buildtags: [core]
    prime:
      - bin/packer
    after: [go]
  go:
    source-tag: go1.8
